### ISSUE TITLE
This GET request should use uppercase GET, not lowercase.

### ISSUE THREAD

**Issue by sue-h-gns** [penguinpowernz/go-geonet#1]
We are about to make changes to the way the GeoNet REST-API is provided that will cause this line to fail as of 25/06/2020.
HTTP methods are all uppercase in Golang, by default. 
All you need to do is change get to GET.
https://github.com/penguinpowernz/go-geonet/blob/2a53fc934f772b38e9e7685f3852b971fd3922a7/client.go#L41

**Comment by penguinpowernz** [comment]
Awesome thank you @sue-h-gns

**Comment by penguinpowernz** [comment]
It is done.
